### ISSUE TITLE
Web app displaying wrong head count.

### ISSUE THREAD

**Issue by MccallisterJ** [davidborland/DiceRoll#1]
The web app on https://lifeislinear.davidson.edu/powerballflip.html sometimes displays the incorrect amount on the coin flip compared to what is displayed in the coin images displayed below after a manual count of the results not only at 28 flips but also when flipping a single (1) coin it would display 2 heads as the count when the image below it showing tails for example.

**Comment by davidborland** [comment]
Should be fixed now.
